"""add ats_checks table and ai_analysis_consented

Revision ID: e7ecbb837f49
Revises: a046e9389276
Create Date: 2026-03-19 10:18:18.500552

"""
from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7ecbb837f49'
down_revision: Union[str, None] = 'a046e9389276'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('resume_updated_at', sa.DateTime(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('format_score', sa.Integer(), nullable=False),
    sa.Column('keyword_score', sa.Integer(), nullable=True),
    sa.Column('content_score', sa.Integer(), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('ai_analysis_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'job_id', name='uq_ats_check_resume_job')
    )
    op.create_index(op.f('ix_ats_checks_job_id'), 'ats_checks', ['job_id'], unique=False)
    op.create_index(op.f('ix_ats_checks_resume_id'), 'ats_checks', ['resume_id'], unique=False)
    op.create_index(op.f('ix_ats_checks_user_id'), 'ats_checks', ['user_id'], unique=False)
    op.add_column('user_profiles', sa.Column('ai_analysis_consented', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'ai_analysis_consented')
    op.drop_index(op.f('ix_ats_checks_user_id'), table_name='ats_checks')
    op.drop_index(op.f('ix_ats_checks_resume_id'), table_name='ats_checks')
    op.drop_index(op.f('ix_ats_checks_job_id'), table_name='ats_checks')
    op.drop_table('ats_checks')
    # ### end Alembic commands ###
