"""add job_matches table

Revision ID: a046e9389276
Revises: ae6845b1d9b9
Create Date: 2026-03-19 00:04:49.422429

"""
from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a046e9389276'
down_revision: Union[str, None] = 'ae6845b1d9b9'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('keyword_score', sa.Integer(), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('skills_match', sa.Integer(), nullable=True),
    sa.Column('experience_match', sa.Integer(), nullable=True),
    sa.Column('education_match', sa.Integer(), nullable=True),
    sa.Column('location_match', sa.Integer(), nullable=True),
    sa.Column('salary_match', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_match_user_job')
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
