"""add tailored_resume table

Revision ID: d71e267bdba5
Revises: e7ecbb837f49
Create Date: 2026-03-19 18:15:56.114001

"""
from __future__ import annotations

from typing import Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd71e267bdba5'
down_revision: Union[str, None] = 'e7ecbb837f49'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailored_resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('tailored_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tailored_experience', sa.JSON(), nullable=True),
    sa.Column('tailored_skills', sa.JSON(), nullable=True),
    sa.Column('keyword_matches', sa.JSON(), nullable=True),
    sa.Column('keyword_gaps', sa.JSON(), nullable=True),
    sa.Column('match_score_before', sa.Integer(), nullable=True),
    sa.Column('match_score_after', sa.Integer(), nullable=True),
    sa.Column('ai_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_job_id'), 'tailored_resumes', ['job_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_resume_id'), 'tailored_resumes', ['resume_id'], unique=False)
    op.create_index(op.f('ix_tailored_resumes_user_id'), 'tailored_resumes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_user_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_resume_id'), table_name='tailored_resumes')
    op.drop_index(op.f('ix_tailored_resumes_job_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    # ### end Alembic commands ###
